/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/* This section of code contains package and import statements.
 * It includes necessary imports for SQL functionality and Swing components.*/
package rms;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author abdul
 */
public class addemployee extends javax.swing.JFrame {
 Connection con=null; // Connection object for database connection
PreparedStatement pst= null; // PreparedStatement object for SQL queries
ResultSet rs= null; // ResultSet object for query results
Statement st= null; // Statement object for executing SQL queries
    /**
     * Creates new form addemployee
     * This constructor initializes the form and establishes a connection to the database.
     */
    public addemployee() {
        initComponents();
         con = RestaurantDBConnection.connectRestaurantDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AddstaffID = new javax.swing.JTextField();
        ename = new javax.swing.JTextField();
        esurname = new javax.swing.JTextField();
        eemail = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        cancelAdEmp = new javax.swing.JButton();
        AddEmp = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Addsalary = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Addwork = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(246, 234, 234));
        jLabel7.setText("Staff ID");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 209, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(246, 234, 234));
        jLabel2.setText("Name");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 209, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(246, 234, 234));
        jLabel4.setText("Surname");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 209, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(246, 234, 234));
        jLabel5.setText("Email");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 209, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(246, 234, 234));
        jLabel6.setText("Phone No");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 209, 60));
        getContentPane().add(AddstaffID, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 390, 50));
        getContentPane().add(ename, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 390, 50));

        esurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esurnameActionPerformed(evt);
            }
        });
        getContentPane().add(esurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 390, 50));

        eemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eemailActionPerformed(evt);
            }
        });
        getContentPane().add(eemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 390, 50));

        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, 390, 50));

        cancelAdEmp.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cancelAdEmp.setText("Cancel");
        cancelAdEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAdEmpActionPerformed(evt);
            }
        });
        getContentPane().add(cancelAdEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, 160, 50));

        AddEmp.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AddEmp.setText("Add");
        AddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpActionPerformed(evt);
            }
        });
        getContentPane().add(AddEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 610, 160, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(246, 234, 234));
        jLabel8.setText("Salary");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 209, 60));
        getContentPane().add(Addsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 390, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(246, 234, 234));
        jLabel9.setText("Work shift");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 209, 60));

        Addwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddworkActionPerformed(evt);
            }
        });
        getContentPane().add(Addwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 390, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("ADD STAFF");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 210, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backGround.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void esurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esurnameActionPerformed

    private void eemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eemailActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void AddworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddworkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddworkActionPerformed

    private void cancelAdEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAdEmpActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelAdEmpActionPerformed

    private void AddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpActionPerformed
        //Retrieve input values
         String staffID = AddstaffID.getText();
    String name = ename.getText();
    String surname = esurname.getText();
    String email = eemail.getText();
    String salary = Addsalary.getText();
    String workShift = Addwork.getText();
    String phoneNumber = phone.getText();
    
    // Validate the required fields
    if (staffID.isEmpty() || name.isEmpty() || surname.isEmpty() || email.isEmpty() || salary.isEmpty() || workShift.isEmpty() || phoneNumber.isEmpty()) {
        // Display a message if any of the required fields are empty
        JOptionPane.showMessageDialog(null, "Please fill in all fields to add an employee.");
        return;  // Exit the method if validation fails
    }
         try{
             // SQL query to insert employee data into the database
            String sql = "INSERT INTO staff(staffID, name, surname, email, salary, workShift, phoneNo) VALUES(?,?,?,?,?,?,?);";
           // Prepare the SQL statement and execute the update: 
            pst= con.prepareStatement(sql);
          pst.setString(1, AddstaffID.getText());
            pst.setString(2, ename.getText());
             pst.setString(3, esurname.getText());
              pst.setString(4, eemail.getText());
               pst.setString(5, Addsalary.getText());
               pst.setString(6, Addwork.getText());
               pst.setString(7, phone.getText());
            pst.executeUpdate();
            con.close();  // Close the connection
            JOptionPane.showMessageDialog(null, "Staff Added"); // Display a success message and go back to staff page
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staff().setVisible(true);
            }
        });
        }
        catch(Exception e)
                {
                     // Exception handling in case of errors
               e.printStackTrace();
               JOptionPane.showMessageDialog(null, "Staff Not Added!");
                
        }
        
    }//GEN-LAST:event_AddEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addemployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmp;
    private javax.swing.JTextField Addsalary;
    private javax.swing.JTextField AddstaffID;
    private javax.swing.JTextField Addwork;
    private javax.swing.JButton cancelAdEmp;
    private javax.swing.JTextField eemail;
    private javax.swing.JTextField ename;
    private javax.swing.JTextField esurname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
