/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rms; // Declares that the addmenu class is part of the "rms" package
import java.sql.*; // Imports the necessary classes from the java.sql package
import javax.swing.JOptionPane; // Imports the JOptionPane class for displaying dialog boxes
/**
 *GUI class for adding a new menu item in a restaurant management system.
 * This class provides a form for entering details of a new menu item.
 * It extends the JFrame class.
 * @author abdul
 */
public class addmenu extends javax.swing.JFrame {
Connection con=null; // Declares a Connection variable for database connection
PreparedStatement pst= null; // Declares a PreparedStatement variable for executing parameterized SQL queries
ResultSet rs= null; // Declares a ResultSet variable for storing query results
Statement st= null; // Declares a Statement variable for executing simple SQL queries
    /**
     * Constructor for the addmenu class.
     * Initializes the GUI components and establishes a database connection.
     * Creates new form addmenu
     */
    public addmenu() {
        initComponents(); // Initializes the GUI components defined in the initComponents() method
        con = RestaurantDBConnection.connectRestaurantDB();  // Establishes a database connection using the RestaurantDBConnection class
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Category = new javax.swing.JTextField();
        AddDescription = new javax.swing.JTextField();
        Addprice = new javax.swing.JTextField();
        Meal = new javax.swing.JTextField();
        itemIDadd = new javax.swing.JTextField();
        canceladd = new javax.swing.JButton();
        ADDmeal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(246, 234, 234));
        jLabel2.setText("Meal Name");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 209, 74));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(246, 234, 234));
        jLabel4.setText("Price");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 209, 74));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(246, 234, 234));
        jLabel5.setText("Description");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 209, 74));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(246, 234, 234));
        jLabel6.setText("Category");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 209, 74));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(246, 234, 234));
        jLabel7.setText("Item ID");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 209, 74));
        getContentPane().add(Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 390, 50));

        AddDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDescriptionActionPerformed(evt);
            }
        });
        getContentPane().add(AddDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 390, 50));

        Addprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddpriceActionPerformed(evt);
            }
        });
        getContentPane().add(Addprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 390, 50));
        getContentPane().add(Meal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 390, 50));
        getContentPane().add(itemIDadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 390, 50));

        canceladd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        canceladd.setText("Cancel");
        canceladd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceladdActionPerformed(evt);
            }
        });
        getContentPane().add(canceladd, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 590, 160, 50));

        ADDmeal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ADDmeal.setText("Add");
        ADDmeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDmealActionPerformed(evt);
            }
        });
        getContentPane().add(ADDmeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 590, 160, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("ADD MENU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 210, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backGround.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddDescriptionActionPerformed

    private void AddpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddpriceActionPerformed

    private void canceladdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceladdActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_canceladdActionPerformed

    private void ADDmealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDmealActionPerformed
        
        // Get the values from the input fields
    String itemID = itemIDadd.getText();
    String mealName = Meal.getText();
    String price = Addprice.getText();
    String category = Category.getText();
    String description = AddDescription.getText();  // This can be empty
    //check if all required fields are filled: 
        if (itemID.isEmpty() || mealName.isEmpty() || price.isEmpty() || category.isEmpty()) {
        // Display a message if any of the required fields are empty
        JOptionPane.showMessageDialog(null, "Please fill in all required fields (item ID, food name, price, category). Description can be left empty.");
        return;  // Exit the method if validation fails
    }
        try{
             // SQL query to insert a new menu item into the database: 
            String sql = "INSERT INTO menu(itemID, foodName, price,description, Category) VALUES(?,?,?,?,?);";
          // Prepare the SQL statement: 
            pst= con.prepareStatement(sql);
          pst.setString(1, itemIDadd.getText());
            pst.setString(2, Meal.getText());
             pst.setString(3, Addprice.getText());
              pst.setString(4, AddDescription.getText());
               pst.setString(5, Category.getText());
               // Execute the SQL statement:
            pst.executeUpdate();
            // Close the database connection:
            con.close();
             // Display a success message:
            JOptionPane.showMessageDialog(null, "Meal Added");
            // Open the menu GUI window:
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        }); 
        }
        catch(Exception e)
                {
                     // Catch any exceptions that occur during the execution of the try block
               e.printStackTrace();
               // Display an error message
               JOptionPane.showMessageDialog(null, "Meal Not Added!");
                
        }
        
    }//GEN-LAST:event_ADDmealActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDmeal;
    private javax.swing.JTextField AddDescription;
    private javax.swing.JTextField Addprice;
    private javax.swing.JTextField Category;
    private javax.swing.JTextField Meal;
    private javax.swing.JButton canceladd;
    private javax.swing.JTextField itemIDadd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
