/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/* This section of code contains package and import statements.
 * It includes necessary imports for SQL functionality and Swing components.*/
package rms;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author abdul
 */
public class editsalary extends javax.swing.JFrame {
Connection con = null; // Connection object for database connection
PreparedStatement pst= null; // PreparedStatement object for SQL queries
ResultSet rs= null; // ResultSet object for query results
Statement st= null; // Statement object for executing SQL queries

    /**
     * Creates new form editsalary
     * This constructor initializes the form and establishes a connection to the database.
     */
    public editsalary() {
        initComponents();
        con= RestaurantDBConnection.connectRestaurantDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        StaffSalary = new javax.swing.JTextField();
        EditSalary = new javax.swing.JTextField();
        cancelEditsalary = new javax.swing.JButton();
        savesalaryedit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(246, 234, 234));
        jLabel8.setText("StaffID");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 209, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(246, 234, 234));
        jLabel9.setText("Salary");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 209, 60));
        getContentPane().add(StaffSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 390, 50));

        EditSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditSalaryActionPerformed(evt);
            }
        });
        getContentPane().add(EditSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 390, 50));

        cancelEditsalary.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cancelEditsalary.setText("Cancel");
        cancelEditsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEditsalaryActionPerformed(evt);
            }
        });
        getContentPane().add(cancelEditsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 160, 50));

        savesalaryedit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        savesalaryedit.setText("Save");
        savesalaryedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savesalaryeditActionPerformed(evt);
            }
        });
        getContentPane().add(savesalaryedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 160, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backGround.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditSalaryActionPerformed

    private void cancelEditsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEditsalaryActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelEditsalaryActionPerformed

    private void savesalaryeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savesalaryeditActionPerformed
        // Retrieve input values: 
        String newSalary = EditSalary.getText();
    String staffID = StaffSalary.getText();
    
    // Validate the required fields
    if (newSalary.isEmpty() || staffID.isEmpty()) {
        // Display a message if either of the required fields is empty
        JOptionPane.showMessageDialog(null, "Please fill in both the new salary and the staff ID.");
        return;  // Exit the method if validation fails
    }
    
         try{
              // Check if the staff ID exists: 
             String checkSql = "SELECT COUNT(*) FROM staff WHERE staffID = ?";
        pst = con.prepareStatement(checkSql);
        pst.setString(1, staffID);
        
        // Execute the query
        ResultSet rs = pst.executeQuery();
        rs.next();
        
        // Check if the staff ID exists
        int count = rs.getInt(1);
        if (count == 0) {
            // Display a message if the staff member does not exist
            JOptionPane.showMessageDialog(null, "The staff member whose salary you are trying to edit doesn't exist.");
            // Close the resources
            rs.close();
            pst.close();
            return;  // Exit the method
        }
        
        // Close the ResultSet and PreparedStatement
        rs.close();
        pst.close();
        // SQL query to update the salary in the database: 
            String sql = "UPDATE staff SET salary=? WHERE staffID= ? ;";
           // Prepare the SQL statement and execute the update: 
            pst= con.prepareStatement(sql);
          pst.setString(1, EditSalary.getText());
            pst.setString(2, StaffSalary.getText());
            pst.executeUpdate();
            // Close the connection
            con.close();
             // Display a success message and go back to staff page
            JOptionPane.showMessageDialog(null, "Salary Updated");
           
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staff().setVisible(true);
            }
        });
        }
        catch(Exception e)
                {
                  // Exception handling in case of errors  
               e.printStackTrace();
               JOptionPane.showMessageDialog(null, "Update Failed!");
                
        }
    }//GEN-LAST:event_savesalaryeditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editsalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editsalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editsalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editsalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editsalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EditSalary;
    private javax.swing.JTextField StaffSalary;
    private javax.swing.JButton cancelEditsalary;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton savesalaryedit;
    // End of variables declaration//GEN-END:variables
}
