/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rms;
import java.sql.*; 
/**
 *
 * @author abdul
 */
public class editlist extends javax.swing.JFrame {
Connection con=null;
PreparedStatement pst =null; 
ResultSet rs= null; 
Statement st= null; 
    /**
     * Creates new form editlist
     */
    public editlist() {
        initComponents();
        con = RestaurantDBConnection.connectRestaurantDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditSalary = new javax.swing.JButton();
        editshift = new javax.swing.JButton();
        Editbackstaff = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EditSalary.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        EditSalary.setText("Edit Salary");
        EditSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditSalaryActionPerformed(evt);
            }
        });
        getContentPane().add(EditSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 240, 110));

        editshift.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        editshift.setText("Edit Work Shift");
        editshift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editshiftActionPerformed(evt);
            }
        });
        getContentPane().add(editshift, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 240, 110));

        Editbackstaff.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Editbackstaff.setText("Back");
        Editbackstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditbackstaffActionPerformed(evt);
            }
        });
        getContentPane().add(Editbackstaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 160, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("EDIT STAFF INFO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 320, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backGround.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditSalaryActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editsalary().setVisible(true);
            }
        });
    }//GEN-LAST:event_EditSalaryActionPerformed

    private void editshiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editshiftActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editworkshift().setVisible(true);
            }
        });
    }//GEN-LAST:event_editshiftActionPerformed

    private void EditbackstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditbackstaffActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staff().setVisible(true);
            }
        });
    }//GEN-LAST:event_EditbackstaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editlist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditSalary;
    private javax.swing.JButton Editbackstaff;
    private javax.swing.JButton editshift;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
