/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rms; // Declares that the editdescription class is part of the "rms" package
import java.sql.*; // Imports the necessary classes from the java.sql package
import javax.swing.JOptionPane; // Imports the JOptionPane class for displaying dialog boxes
/**
 *GUI class for editing the description of a menu item in a restaurant management system.
 * This class provides options to edit the description of a menu item.
 * It extends the JFrame class.
 * @author abdul
 */
public class editdescription extends javax.swing.JFrame {
Connection con=null;  // Declares a Connection variable for database connection
PreparedStatement pst= null; // Declares a PreparedStatement variable for executing parameterized SQL queries
ResultSet rs= null; // Declares a ResultSet variable for storing query results
Statement st= null; // Declares a Statement variable for executing simple SQL queries
    /**
     * Creates new form editdescription
     *  Initializes the GUI components and establishes a database connection.
     */
    public editdescription() {
        initComponents();  // Initializes the GUI components defined in the initComponents() method
        con = RestaurantDBConnection.connectRestaurantDB(); // Establishes a database connection using the RestaurantDBConnection class
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        itemDes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Description = new javax.swing.JTextField();
        canceleditmenudesc = new javax.swing.JButton();
        Savemenudesc = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(246, 234, 234));
        jLabel7.setText("Item ID");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 209, 74));

        itemDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDesActionPerformed(evt);
            }
        });
        getContentPane().add(itemDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 390, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(246, 234, 234));
        jLabel2.setText("Description");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 209, 74));
        getContentPane().add(Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 390, 50));

        canceleditmenudesc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        canceleditmenudesc.setText("Cancel");
        canceleditmenudesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceleditmenudescActionPerformed(evt);
            }
        });
        getContentPane().add(canceleditmenudesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 160, 50));

        Savemenudesc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Savemenudesc.setText("Save");
        Savemenudesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavemenudescActionPerformed(evt);
            }
        });
        getContentPane().add(Savemenudesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 160, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backGround.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemDesActionPerformed

    private void canceleditmenudescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceleditmenudescActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_canceleditmenudescActionPerformed

    private void SavemenudescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavemenudescActionPerformed
         // Get the description text and item ID from the input fields
         String descriptionText = Description.getText();
    String itemID = itemDes.getText();
    
    // Validate the required fields
    if (descriptionText.isEmpty() || itemID.isEmpty()) {
        // Display a message if either the description or item ID field is empty
        JOptionPane.showMessageDialog(null, "Please fill in both the description and the item ID.");
        return;  // Exit the method if validation fails
    }
        try{
            // SQL query to count the number of rows in the 'menu' table where the 'itemID' matches the provided itemID
             String checkSql = "SELECT COUNT(*) FROM menu WHERE itemID = ?";
             // Creating a PreparedStatement object to execute the SQL query
        pst = con.prepareStatement(checkSql);
        // Setting the parameter (itemID) for the PreparedStatement
        pst.setString(1, itemID);
        
        // Execute the query
        ResultSet rs = pst.executeQuery();
        // Moving the cursor to the first row of the ResultSet
        rs.next();
        
        // Check if the item ID exists
        int count = rs.getInt(1);
        if (count == 0) {
            // Display a message if the meal does not exist
            JOptionPane.showMessageDialog(null, "The meal whose description you are trying to edit doesn't exist.");
            // Close the resources
            rs.close();
            pst.close();
            return;  // Exit the method
        }
        
        // Close the ResultSet and PreparedStatement
        rs.close();
        pst.close();
         // Update the description in the database
            String sql = "UPDATE menu SET description=? WHERE itemID= ? ;";
          
            pst= con.prepareStatement(sql);
          pst.setString(1, Description.getText());
            pst.setString(2, itemDes.getText());
            pst.executeUpdate();
            // Close connection
            con.close();
             // Display a success message and open the menu GUI window
            JOptionPane.showMessageDialog(null, "Description Updated");
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        }); 
        }
        catch(Exception e)
                {
                // Display an error message if an exception occurs    
               e.printStackTrace();
               JOptionPane.showMessageDialog(null, "Update Failed!");
                
        }
        
       
    }//GEN-LAST:event_SavemenudescActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editdescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editdescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editdescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editdescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editdescription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Description;
    private javax.swing.JButton Savemenudesc;
    private javax.swing.JButton canceleditmenudesc;
    private javax.swing.JTextField itemDes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
