/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rms; // Declares that the editmenu class is part of the "rms" package
import java.sql.*; // Imports the necessary classes from the java.sql package
import javax.swing.JOptionPane; // Imports the JOptionPane class for displaying dialog boxes
/**
 *GUI class for editing menu items in a restaurant management system.
 * This class provides options to edit the price and description of a menu item.
 * It extends the JFrame class.
 * @author abdul
 */
public class editmenu extends javax.swing.JFrame {
 Connection con=null; // Declares a Connection variable for database connection
PreparedStatement pst= null; // Declares a PreparedStatement variable for executing parameterized SQL queries
ResultSet rs= null; // Declares a ResultSet variable for storing query results
Statement st= null; // Declares a Statement variable for executing simple SQL queries
    /**
     * Creates new form editmenu
     *  Initializes the GUI components and establishes a database connection.
     */
    public editmenu() {
         // Initializes the GUI components defined in the initComponents() method
        initComponents();
        con = RestaurantDBConnection.connectRestaurantDB();  // Establishes a database connection using the RestaurantDBConnection class
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editDescription = new javax.swing.JButton();
        editPrice = new javax.swing.JButton();
        backtomenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editDescription.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        editDescription.setText("Edit Description");
        editDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDescriptionActionPerformed(evt);
            }
        });
        getContentPane().add(editDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 240, 110));

        editPrice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        editPrice.setText("Edit Price");
        editPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPriceActionPerformed(evt);
            }
        });
        getContentPane().add(editPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 240, 110));

        backtomenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backtomenu.setText("Back");
        backtomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtomenuActionPerformed(evt);
            }
        });
        getContentPane().add(backtomenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 160, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("EDIT MENU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 210, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backGround.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1200, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPriceActionPerformed
        // // Open the editprice GUI window
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editprice().setVisible(true);
            }
        });
    }//GEN-LAST:event_editPriceActionPerformed

    private void editDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDescriptionActionPerformed
        // // Open the editdescription GUI window
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editdescription().setVisible(true);
            }
        });
    }//GEN-LAST:event_editDescriptionActionPerformed

    private void backtomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtomenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backtomenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtomenu;
    private javax.swing.JButton editDescription;
    private javax.swing.JButton editPrice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
