/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/* This section of code contains package and import statements.
 * It includes necessary imports for SQL functionality and Swing components.*/
package rms; 
import java.sql.*; 
import javax.swing.JOptionPane;
/**
 *This class represents the user interface for editing work shifts.
 * @author abdul
 */
public class editworkshift extends javax.swing.JFrame {
Connection con = null; // Connection object for database connection
PreparedStatement pst= null; // PreparedStatement object for SQL queries
ResultSet rs= null; // ResultSet object for query results
Statement st= null; // Statement object for executing SQL queries
    /**
     * Creates new form editworkshift
     * This constructor initializes the form and establishes a connection to the database.
     */
    public editworkshift() {
        initComponents();
        con= RestaurantDBConnection.connectRestaurantDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        StIDWork = new javax.swing.JTextField();
        WorkshiftEdit = new javax.swing.JTextField();
        cancelEditworkshift = new javax.swing.JButton();
        SaveWork = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(246, 234, 234));
        jLabel8.setText("StaffID");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 209, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(246, 234, 234));
        jLabel9.setText("Work Shift");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 209, 60));
        getContentPane().add(StIDWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 390, 50));

        WorkshiftEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkshiftEditActionPerformed(evt);
            }
        });
        getContentPane().add(WorkshiftEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 390, 50));

        cancelEditworkshift.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cancelEditworkshift.setText("Cancel");
        cancelEditworkshift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEditworkshiftActionPerformed(evt);
            }
        });
        getContentPane().add(cancelEditworkshift, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 160, 50));

        SaveWork.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SaveWork.setText("Save");
        SaveWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveWorkActionPerformed(evt);
            }
        });
        getContentPane().add(SaveWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 160, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backGround.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WorkshiftEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkshiftEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WorkshiftEditActionPerformed

    private void cancelEditworkshiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEditworkshiftActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelEditworkshiftActionPerformed

    private void SaveWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveWorkActionPerformed
        // Retrieve input values
        String newWorkShift = WorkshiftEdit.getText();
    String staffID = StIDWork.getText();
    
    // Validate the required fields
    if (newWorkShift.isEmpty() || staffID.isEmpty()) {
        // Display a message if either of the required fields is empty
        JOptionPane.showMessageDialog(null, "Please fill in both the new work shift and the staff ID.");
        return;  // Exit the method if validation fails
    }
        try{
             // Check if the staff ID exists
            String checkSql = "SELECT COUNT(*) FROM staff WHERE staffID = ?";
        pst = con.prepareStatement(checkSql);
        pst.setString(1, staffID);
        
        // Execute the query
        ResultSet rs = pst.executeQuery();
        rs.next();
        
        // Check if the staff ID exists
        int count = rs.getInt(1);
        if (count == 0) {
            // Display a message if the staff member does not exist
            JOptionPane.showMessageDialog(null, "The staff member whose work shift you are trying to edit doesn't exist.");
            // Close the resources
            rs.close();
            pst.close();
            return;  // Exit the method
        }
        
        // Close the ResultSet and PreparedStatement
        rs.close();
        pst.close();
        // SQL query to update the work shift in the database:
            String sql = "UPDATE staff SET workShift=? WHERE staffID= ? ;";
           // Prepare the SQL statement and execute update: 
            pst= con.prepareStatement(sql);
          pst.setString(1, WorkshiftEdit.getText());
            pst.setString(2, StIDWork.getText());
            pst.executeUpdate();
            // Close the connection: 
            con.close();
            // Display a success message then go to staff page again: 
            JOptionPane.showMessageDialog(null, "Work Shift Updated");
           
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staff().setVisible(true);
            }
        });
        }
        catch(Exception e)
                {
                  // Exception handling in case of errors  
               e.printStackTrace();
               JOptionPane.showMessageDialog(null, "Update Failed!");
                
        }
    }//GEN-LAST:event_SaveWorkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editworkshift.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editworkshift.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editworkshift.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editworkshift.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editworkshift().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveWork;
    private javax.swing.JTextField StIDWork;
    private javax.swing.JTextField WorkshiftEdit;
    private javax.swing.JButton cancelEditworkshift;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
