/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rms; // Declares that the menu class is part of the "rms" package
import java.sql.*; // Imports the necessary classes from the java.sql package
import javax.swing.JOptionPane; // Imports the JOptionPane class for displaying dialog boxes
import javax.swing.table.DefaultTableModel; // Imports the DefaultTableModel class for managing table data

/**
 *GUI class for managing the menu in a restaurant management system.
 * This class provides functionalities for browsing, adding, editing, and removing items from the menu.
 * It extends the JFrame class.
 * @author abdul
 */
public class menu extends javax.swing.JFrame { 
    Connection con=null; // Declares a Connection variable for database connection
PreparedStatement pst= null; // Declares a PreparedStatement variable for executing parameterized SQL queries
ResultSet rs= null; // Declares a ResultSet variable for storing query results
Statement st= null; // Declares a Statement variable for executing simple SQL queries

    /**
     * Creates new form menu
     * Constructor for the menu class.
     * Initializes the GUI components and establishes a database connection.
     */
    public menu() {
        con = RestaurantDBConnection.connectRestaurantDB();
        // Establishes a database connection using the RestaurantDBConnection class
        initComponents();
        // Initializes the GUI components defined in the initComponents() method
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RemoveMenu = new javax.swing.JButton();
        BrowseMenu = new javax.swing.JButton();
        AddMenu = new javax.swing.JButton();
        EditMenu = new javax.swing.JButton();
        home1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RemoveMenu.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        RemoveMenu.setText("Remove From Menu");
        RemoveMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveMenuActionPerformed(evt);
            }
        });
        getContentPane().add(RemoveMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, 240, 80));

        BrowseMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BrowseMenu.setText("Browse Menu");
        BrowseMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseMenuActionPerformed(evt);
            }
        });
        getContentPane().add(BrowseMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 200, 80));

        AddMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AddMenu.setText("Add To Menu");
        AddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMenuActionPerformed(evt);
            }
        });
        getContentPane().add(AddMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 200, 80));

        EditMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        EditMenu.setText("Edit Menu");
        EditMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditMenuActionPerformed(evt);
            }
        });
        getContentPane().add(EditMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 200, 80));

        home1.setFont(new java.awt.Font("Vivaldi", 3, 18)); // NOI18N
        home1.setText("Home");
        home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home1ActionPerformed(evt);
            }
        });
        getContentPane().add(home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "itemID", "foodName", "price", "description", "Category"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 910, 420));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backGround.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMenuActionPerformed
        // Opens the addmenu GUI window
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addmenu().setVisible(true);
            }
        });
    }//GEN-LAST:event_AddMenuActionPerformed
 /**
     * Event handler for the "Browse Menu" button.
     * Displays the menu items in a table.
     */
    private void BrowseMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseMenuActionPerformed
        // Executes a query to retrieve all menu items from the database and displays them in a table
        try{ 
            String sql = "SELECT * FROM menu;"; // SQL query to select all columns from the 'menu' table
           st= con.createStatement(); // Creates a Statement object for executing SQL queries
rs = st.executeQuery(sql); // Executes the SQL query and stores the result in the ResultSet rs
while (rs.next()){ // Iterates over the result set
     // Retrieves data from the current row of the result set
    String itemID= rs.getString("itemID");
    String foodName= rs.getString("foodName");
    String price = rs.getString("price");
    String description = rs.getString("description");
    String Category= rs.getString("Category");
     // Creates an array to hold the data of the current row
    String Rtable[]= {itemID, foodName, price, description, Category};
    // Gets the DefaultTableModel of the jTable1 component
    DefaultTableModel tmodel= (DefaultTableModel) jTable1.getModel();
     // Adds a row to the table with the data from the current row of the result set
    tmodel.addRow(Rtable); 
}
con.close(); // Closes the database connection
            }
     
        
        catch(Exception e)
                {  
                    // Catches any exceptions that occur during the execution of the try block
        }

        
    }//GEN-LAST:event_BrowseMenuActionPerformed

    private void EditMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditMenuActionPerformed
        // // Opens the editmenu GUI window
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editmenu().setVisible(true);
            }
        });
    }//GEN-LAST:event_EditMenuActionPerformed

    private void RemoveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveMenuActionPerformed
        // // Opens remove GUI window
        
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new remove().setVisible(true);
            }
        });
    }//GEN-LAST:event_RemoveMenuActionPerformed

    private void home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home1ActionPerformed
        // // Opens the homepage GUI window
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }//GEN-LAST:event_home1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMenu;
    private javax.swing.JButton BrowseMenu;
    private javax.swing.JButton EditMenu;
    private javax.swing.JButton RemoveMenu;
    private javax.swing.JButton home1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
