/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/* This section of code contains package and import statements.
 * It includes necessary imports for SQL functionality and Swing components.*/
package rms; 
import java.sql.*; 
import javax.swing.JOptionPane;
/**
 *This class represents the user interface for removing an employee.
 * @author abdul
 */
public class removeemployee extends javax.swing.JFrame {
    Connection con= null; // Connection object for database connection
    PreparedStatement pst= null;  // PreparedStatement object for SQL queries
    ResultSet rs= null; // ResultSet object for query results
     Statement st= null; // Statement object for executing SQL queries
 
    /**
     * Creates new form removeemployee
     * This constructor initializes the form and establishes a connection to the database.
     */
    public removeemployee() {
        initComponents(); // Method to initialize components of the form
        con= RestaurantDBConnection.connectRestaurantDB(); // Establish database connection
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        SIDelete = new javax.swing.JTextField();
        CancelRemoveEmp = new javax.swing.JButton();
        DeleteStaff = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(246, 234, 234));
        jLabel7.setText("Staff ID");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 209, 74));
        getContentPane().add(SIDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 390, 50));

        CancelRemoveEmp.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CancelRemoveEmp.setText("Cancel");
        CancelRemoveEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelRemoveEmpActionPerformed(evt);
            }
        });
        getContentPane().add(CancelRemoveEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 160, 50));

        DeleteStaff.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        DeleteStaff.setText("Delete");
        DeleteStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteStaffActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 160, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("REMOVE STAFF");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 290, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backGround.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelRemoveEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelRemoveEmpActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelRemoveEmpActionPerformed

    private void DeleteStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteStaffActionPerformed
        // Retrieve the staff ID from the text field  
        String staffID = SIDelete.getText();
    
    // Validate the required field
    if (staffID.isEmpty()) {
        // Display a message if the staff ID field is empty
        JOptionPane.showMessageDialog(null, "Please fill in the staff ID to delete a staff member.");
        return;  // Exit the method if validation fails
    }
    
           try{
               // Check if the staff ID exists before deletion
               String checkSql = "SELECT COUNT(*) FROM staff WHERE staffID = ?";
        pst = con.prepareStatement(checkSql);
        pst.setString(1, staffID);
        
        // Execute the query
        ResultSet rs = pst.executeQuery();
        rs.next();
        
        // Check if the staff ID exists
        int count = rs.getInt(1);
        if (count == 0) {
            // Display a message if the staff ID does not exist
            JOptionPane.showMessageDialog(null, "The staff member you are trying to delete does not exist.");
            return;  // Exit the method
        }
        
        // Close the ResultSet and PreparedStatement
        rs.close();
        pst.close();
        // SQL query to delete the staff member from the database
            String sql = "DELETE FROM staff WHERE staffID=?;";
          // Prepare the SQL statement
            pst= con.prepareStatement(sql);
               pst.setString(1, SIDelete.getText());
                // Execute the update and close the connection: 
            pst.executeUpdate();
            con.close();
            // Display a success messa and go back to staff page: 
            JOptionPane.showMessageDialog(null, "Staff Member Deleted");
           
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staff().setVisible(true);
            }
        });
        }
        catch(Exception e)
                {
                 // Exception handling in case of errors    
               e.printStackTrace();
               JOptionPane.showMessageDialog(null,"Staff Member Not Deleted!");
                
        }
                       
    }//GEN-LAST:event_DeleteStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(removeemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(removeemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(removeemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(removeemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new removeemployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelRemoveEmp;
    private javax.swing.JButton DeleteStaff;
    private javax.swing.JTextField SIDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
