/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rms;  // Declares that the remove class is part of the "rms" package
// Importing necessary Java SQL and Swing components
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *JFrame class for removing a meal from the menu.
 * @author abdul
 */
public class remove extends javax.swing.JFrame {
 Connection con=null; // Database connection object
PreparedStatement pst= null;  // Prepared statement for executing SQL queries
ResultSet rs= null;  // Result set for storing the results of SQL queries
Statement st= null; // Statement object for executing SQL queries
    /**
     * Creates new form remove
     */
    public remove() {
        initComponents();  // Initializing the GUI components
         con = RestaurantDBConnection.connectRestaurantDB();   // Establishing a database connection
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        MealID = new javax.swing.JTextField();
        cancelremove = new javax.swing.JButton();
        removeMEAL = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(246, 234, 234));
        jLabel7.setText("Item ID");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 209, 74));
        getContentPane().add(MealID, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 390, 50));

        cancelremove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cancelremove.setText("Cancel");
        cancelremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelremoveActionPerformed(evt);
            }
        });
        getContentPane().add(cancelremove, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 160, 50));

        removeMEAL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        removeMEAL.setText("Delete");
        removeMEAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMEALActionPerformed(evt);
            }
        });
        getContentPane().add(removeMEAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 160, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("REMOVE MEAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 280, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backGround.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelremoveActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelremoveActionPerformed

    private void removeMEALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMEALActionPerformed
        // Getting the meal ID entered by the user
         String mealIDText = MealID.getText();
    
    // Validate the required field
    if (mealIDText.isEmpty()) {
        // Display a message if the item ID field is empty
        JOptionPane.showMessageDialog(null, "Please fill in the item ID to remove a meal.");
        return;  // Exit the method if validation fails
    }
         try{
             // SQL query to check if the item ID exists in the database
             String checkSql = "SELECT COUNT(*) FROM menu WHERE itemID = ?";
        pst = con.prepareStatement(checkSql);
        pst.setString(1, mealIDText);
        
        // Execute the query
        ResultSet rs = pst.executeQuery();
        rs.next();
        
        // Check if the item ID exists
        int count = rs.getInt(1);
        if (count == 0) {
            // Display a message if the meal does not exist
            JOptionPane.showMessageDialog(null, "The meal you are trying to remove does not exist.");
            // Close the resources
            rs.close();
            pst.close();
            return;  // Exit the method
        }
        
        // Close the ResultSet and PreparedStatement
        rs.close();
        pst.close();
         // SQL query to delete the meal from the menu
            String sql = "DELETE FROM menu WHERE itemID=?;";
          
            pst= con.prepareStatement(sql);
               pst.setString(1, MealID.getText());
            pst.executeUpdate();
             // Closing the database connection and displaying success message, then going back to menu window
            con.close();
            JOptionPane.showMessageDialog(null, "Meal Deleted");
           
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        }); 
        }
        catch(Exception e)
                {
                  // Catching and handling any exceptions   
               e.printStackTrace();
               // Displaying an error message
               JOptionPane.showMessageDialog(null, "Meal Not Deleted!");
                
        }
    }//GEN-LAST:event_removeMEALActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new remove().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MealID;
    private javax.swing.JButton cancelremove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton removeMEAL;
    // End of variables declaration//GEN-END:variables
}
